DROP TABLE PRODUCT_TABLE

CREATE TABLE PRODUCT_TABLE (
ID INT NOT NULL PRIMARY KEY,
NAME VARCHAR(200) NOT NULL,
LOCATION VARCHAR(50) NOT NULL,
SCHEDULE VARCHAR(50) NOT NULL,
PRICE DECIMAL(18, 2) NOT NULL,
DESCRIPTION VARCHAR(500) NOT NULL,
UPDATED_DATE DATETIME NOT NULL,
CREATED_DATE DATETIME NOT NULL,
UPDATED_USER VARCHAR(50) NOT NULL,
CREATED_USER VARCHAR(50) NOT NULL,
CONSTRAINT UC_PRODUCT_CONSTRAINT UNIQUE (NAME, LOCATION, SCHEDULE, PRICE),
)