DROP TABLE USER_PRODUCT_TABLE;
DROP TABLE USER_TABLE;
DROP TABLE PRODUCT_TABLE;
DROP TABLE CONFIGURATION_TABLE;

CREATE TABLE USER_TABLE (
  USER_ID INT NOT NULL IDENTITY,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  PHONE_NUMBER VARCHAR(50) NOT NULL,
  STREET_ADDRESS VARCHAR(100) NOT NULL,
  CITY VARCHAR(50) NOT NULL,
  STATE VARCHAR(50) NOT NULL,
  ZIP VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(50) NOT NULL,
  FAMILY_GOTHRAM VARCHAR(50),
  PRIMARY_NAKSHATHRAM VARCHAR(50),
  PRIMARY_PADAM VARCHAR(50),
  SPOUSE_NAME VARCHAR(50),
  SPOUSE_NAKSHATHRAM VARCHAR(50),
  SPOUSE_PADAM VARCHAR(50),
  CHILD1_NAME VARCHAR(50),
  CHILD1_NAKSHATHRAM VARCHAR(50),
  CHILD1_PADAM VARCHAR(50),
  CHILD2_NAME VARCHAR(50),
  CHILD2_NAKSHATHRAM VARCHAR(50),
  CHILD2_PADAM VARCHAR(50),
  CHILD3_NAME VARCHAR(50),
  CHILD3_NAKSHATHRAM VARCHAR(50),
  CHILD3_PADAM VARCHAR(50),
  CHILD4_NAME VARCHAR(50),
  CHILD4_NAKSHATHRAM VARCHAR(50),
  CHILD4_PADAM VARCHAR(50),
  IS_ADMIN VARCHAR(50),
  UPDATED_DATE DATETIME,
  CREATED_DATE DATETIME,
  UPDATED_USER VARCHAR(50),
  CREATED_USER VARCHAR(50),
  PRIMARY KEY (USER_ID),
  CONSTRAINT UNI_FIRST_NAME UNIQUE (FIRST_NAME),
  CONSTRAINT UNI_LAST_NAME UNIQUE (LAST_NAME),
  CONSTRAINT UNI_EMAIL UNIQUE (EMAIL),
  CONSTRAINT UNI_PHONE_NUMBER UNIQUE (PHONE_NUMBER)
);

CREATE TABLE PRODUCT_TABLE (
  PRODUCT_ID INT NOT NULL IDENTITY,
  NAME VARCHAR(200) NOT NULL,
  LOCATION VARCHAR(50) NOT NULL,
  SCHEDULE VARCHAR(50) NOT NULL,
  PRICE DECIMAL(10, 2) NOT NULL,
  DESCRIPTION VARCHAR(500) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_USER VARCHAR(50) NOT NULL,
  CREATED_USER VARCHAR(50) NOT NULL,
  PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE USER_PRODUCT_TABLE (
  USER_PRODUCT_ID INT NOT NULL IDENTITY,
  USER_ID INT NOT NULL,
  PRODUCT_ID INT NOT NULL,
  ORDER_NUMBER VARCHAR(20) NOT NULL,
  NOTES VARCHAR(500),
  STATUS VARCHAR(50) NOT NULL,
  DATE_TIME DATETIME,
  UPDATED_DATE DATETIME NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_USER VARCHAR(50) NOT NULL,
  CREATED_USER VARCHAR(50) NOT NULL,
  CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID)
             REFERENCES PRODUCT_TABLE (PRODUCT_ID),
  CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID)
             REFERENCES USER_TABLE (USER_ID)
);

CREATE TABLE CONFIGURATION_TABLE (
  CONFIGURATION_ID INT NOT NULL IDENTITY,
  CONFIGURATION_NAME VARCHAR(100) NOT NULL,
  VALUE VARCHAR(100) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_USER VARCHAR(50) NOT NULL,
  CREATED_USER VARCHAR(50) NOT NULL,
  PRIMARY KEY (CONFIGURATION_ID),
  CONSTRAINT UNI_CONFIGURATION_NAME UNIQUE (CONFIGURATION_NAME)
);

Insert into CONFIGURATION_TABLE (CONFIGURATION_NAME, VALUE, UPDATED_DATE, CREATED_DATE, UPDATED_USER, CREATED_USER)
values ('recipients','manu_may@yahoo.com, manudr@hotmail.com',getdate(),getdate(),'Manu','Manu');

Insert into USER_TABLE (FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,STREET_ADDRESS,CITY,STATE,ZIP,PASSWORD,FAMILY_GOTHRAM,PRIMARY_NAKSHATHRAM,PRIMARY_PADAM,SPOUSE_NAME,SPOUSE_NAKSHATHRAM,SPOUSE_PADAM,CHILD1_NAME,CHILD1_NAKSHATHRAM,CHILD1_PADAM,CHILD2_NAME,CHILD2_NAKSHATHRAM,CHILD2_PADAM,CHILD3_NAME,CHILD3_NAKSHATHRAM,CHILD3_PADAM,CHILD4_NAME,CHILD4_NAKSHATHRAM,CHILD4_PADAM,IS_ADMIN,UPDATED_DATE,CREATED_DATE,UPDATED_USER,CREATED_USER) 
values ('Test','Test','test@test.com','7868767868','jhkjhkjhkj','kjhkjh','nbmnbmn','67576','password','nbvnvnbv','lkjlkjk','','','','','','','','','','','','','','','','','N',getdate(),getdate(),'Manu','Manu');

Insert into PRODUCT_TABLE (NAME,LOCATION,SCHEDULE,PRICE,DESCRIPTION,UPDATED_DATE,CREATED_DATE,UPDATED_USER,CREATED_USER)
values ('Sri Mahalakshmi Abhishekam Kumkumarchana', 'Temple', 'Special Event', 51.00, 'Sri Mahalakshmi Abhishekam Kumkumarchana', GETDATE(), GETDATE(), 'Manu', 'Manu');

Insert into PRODUCT_TABLE (NAME,LOCATION,SCHEDULE,PRICE,DESCRIPTION,UPDATED_DATE,CREATED_DATE,UPDATED_USER,CREATED_USER)
values ('Sri Mahalakshmi Astothara Kumkumarchana', 'Temple', 'Special Event', 31.00, 'Sri Mahalakshmi Astothara Kumkumarchana', GETDATE(), GETDATE(), 'Manu', 'Manu');

Insert into PRODUCT_TABLE (NAME,LOCATION,SCHEDULE,PRICE,DESCRIPTION,UPDATED_DATE,CREATED_DATE,UPDATED_USER,CREATED_USER)
values ('Unjal Seva', 'Temple', 'Special Event', 51.00, 'Unjal Seva', GETDATE(), GETDATE(), 'Manu', 'Manu');

Insert into PRODUCT_TABLE (NAME,LOCATION,SCHEDULE,PRICE,DESCRIPTION,UPDATED_DATE,CREATED_DATE,UPDATED_USER,CREATED_USER)
values ('Grand Sponsor (All of the above)', 'Temple', 'Special Event', 116.00, 'Grand Sponsor (All of the above)', GETDATE(), GETDATE(), 'Manu', 'Manu');