DROP TABLE USER_PRODUCT_TABLE;
DROP TABLE USER_TABLE;
DROP TABLE PRODUCT_TABLE;

CREATE TABLE USER_TABLE (
  USER_ID INT NOT NULL IDENTITY,
  USER_CODE VARCHAR(10) NOT NULL,
  USER_NAME VARCHAR(20) NOT NULL,
  PRIMARY KEY (USER_ID),
  CONSTRAINT UNI_USER_NAME UNIQUE (USER_NAME),
  CONSTRAINT UNI_USER_ID UNIQUE (USER_CODE)
);

CREATE TABLE PRODUCT_TABLE (
  PRODUCT_ID INT NOT NULL IDENTITY,
  NAME VARCHAR(200) NOT NULL,
  LOCATION VARCHAR(50) NOT NULL,
  SCHEDULE VARCHAR(50) NOT NULL,
  PRICE DECIMAL(18, 2) NOT NULL,
  DESCRIPTION VARCHAR(500) NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_USER VARCHAR(50) NOT NULL,
  CREATED_USER VARCHAR(50) NOT NULL,
  PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE  USER_PRODUCT_TABLE (
  USER_ID INT NOT NULL,
  PRODUCT_ID INT NOT NULL,
  NOTES VARCHAR(500),
  STATUS VARCHAR(50) NOT NULL,
  DATE_TIME DATETIME NOT NULL,
  UPDATED_DATE DATETIME NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_USER VARCHAR(50) NOT NULL,
  CREATED_USER VARCHAR(50) NOT NULL,
  PRIMARY KEY (USER_ID,PRODUCT_ID),
  CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID)
             REFERENCES PRODUCT_TABLE (PRODUCT_ID),
  CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID)
             REFERENCES USER_TABLE (USER_ID)
);