DROP TABLE STOCK_CATEGORY;
DROP TABLE STOCK;
DROP TABLE CATEGORY;

CREATE TABLE STOCK (
  STOCK_ID INT NOT NULL IDENTITY,
  STOCK_CODE VARCHAR(10) NOT NULL,
  STOCK_NAME VARCHAR(20) NOT NULL,
  PRIMARY KEY (STOCK_ID),
  CONSTRAINT UNI_STOCK_NAME UNIQUE (STOCK_NAME),
  CONSTRAINT UNI_STOCK_ID UNIQUE (STOCK_CODE)
);

CREATE TABLE CATEGORY (
  CATEGORY_ID INT NOT NULL IDENTITY,
  NAME VARCHAR(10) NOT NULL,
  DESCR VARCHAR(255) NOT NULL,
  PRIMARY KEY (CATEGORY_ID)
);

CREATE TABLE  STOCK_CATEGORY (
  STOCK_ID INT NOT NULL,
  CATEGORY_ID INT NOT NULL,
  CREATED_DATE DATE NOT NULL,
  CREATED_BY VARCHAR(10) NOT NULL,
  PRIMARY KEY (STOCK_ID,CATEGORY_ID),
  CONSTRAINT FK_CATEGORY_ID FOREIGN KEY (CATEGORY_ID)
             REFERENCES CATEGORY (CATEGORY_ID),
  CONSTRAINT FK_STOCK_ID FOREIGN KEY (STOCK_ID)
             REFERENCES STOCK (STOCK_ID)
);